import "dotenv/config"; // Configures the environment configurations from the .env file

import { GoogleGenerativeAI } from "@google/generative-ai"; // Imports the GoogleGenerativeAI library from the package @google/generative-ai

const genAI = new GoogleGenerativeAI(process.env.API_KEY); // Creates a new instance of GoogleGenerativeAI and passes in your API key

const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash-8b" }); // Specifying the model you want to use

const prompt = "Tell me a joke about programming."; // Prompt that you will send to the Gemini model

const result = await model.generateContent(prompt); // Sends your prompt to the Gemini model and waits for it to respond

console.log(result.response.text()); // Extracts the actual text generated by Gemini so you can see the output